### ISSUE TITLE
v0.0.2 Roadmap

### ISSUE THREAD

**Issue by Bidaya0** [Bidaya0/gbatect#7]
# Roadmap

## N+1 

- [ ] bidirectional conversion between docker-compose and batect
- [ ] basic support Kubernetes 
- [ ] convert `docker run` command to batect container

## v0.0.2
- [ ] update exists batect.yml
	- [ ] show diff between exists batect.yml and updated one
	- [ ] update and keep origin format
	- [ ] choose update parts of batect.yml
- [ ] serve as a web service
	- [x] offer basic online convert 
	- [ ] ui design
